### ISSUE TITLE
Broken dependency ?? in densenet_layer.py

### ISSUE THREAD

**Issue by anees042** [pannous/tensorflow-speech-recognition#23]
Not able to run densenet_layer.py; getting the error below;

`Traceback (most recent call last):
  File "densenet_layer.py", line 4, in <module>
    import layer
  File "D:\git\AI\tensorflow-speech-recognition\layer\__init__.py", line 1, in <module>
    from net import *
ImportError: No module named 'net'`

i fixed the problem with;

from .net import *
  File "D:\git\AI\tensorflow-speech-recognition\layer\__init__.py", line 1, in <module>

Running on windows 10, tensorflow 0.12, python3.5

Thanks..

**Comment by pannous** [comment]
thx
