### ISSUE TITLE
spoken_words_wav.tar

### ISSUE THREAD

**Issue by altbit** [pannous/tensorflow-speech-recognition#33]
Could you, please, upload spoken_words_wav.tar somewhere?
Thank you.

**Comment by pannous** [comment]
Dropbox  blocked that file, but you can generate it yourself.
Look at ./generate_speech_data.py if you are on a Mac, the same approach would also work on other systems.

**Comment by altbit** [comment]
OK, thanks. I'll try.

**Comment by psilva07** [comment]
I'm also trying to generate this data, but I haven't succeeded.  When running that script the function check_voices() is called before main and it gives the following error:

```
Traceback (most recent call last):
  File "generate_speech_data.py", line 125, in <module>
    check_voices()
  File "generate_speech_data.py", line 108, in check_voices
    voice_infos=str(subprocess.check_output(["say", "-v?"])).split("\n")[:-2]
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Even if I comment that the script fails because there is no file called wordlist.txt:

```
Traceback (most recent call last):
  File "generate_speech_data.py", line 218, in <module>
    main()
  File "generate_speech_data.py", line 214, in main
    spoken_words()
  File "generate_speech_data.py", line 195, in spoken_words
    words= open(wordlist).readlines()
IOError: [Errno 2] No such file or directory: 'wordlist.txt'
```
Is this just a file with words we want to be generated? If so, what's the format?

**Comment by haneesh11** [comment]
I get errors too while generating speech data. Is there any other place, where we can download the speech_words_wav.tar file?

https://dl.dropboxusercontent.com/u/23615316/spoken_words.tar

**Comment by 4emkay** [comment]
from this link  you can download the data.
http://pannous.net/files/
Thank You.
