### ISSUE TITLE
ImportError: No module named layer while running densenet_layer.py

### ISSUE THREAD

**Issue by manishanker** [pannous/tensorflow-speech-recognition#34]
Hi,

I could not run densenet_layer.py since it throws import error of the module layer. 

**Traceback (most recent call last):
  File "densenet_layer.py", line 6, in <module>
    import layer
ImportError: No module named layer**

From my understanding, this is layers in tflearn. But the model architecture defined here doesnt work
net = layer.net(simple_dense, input_shape=(width,height), output_width=classes, learning_rate=0.01)

Thanks
Manishanker

**Comment by pannous** [comment]
`git clone --recursive https://github.com/pannous/tensorflow-speech-recognition`
or
`pip install layer`

**Comment by manishanker** [comment]
Wow, thanks for super fast reply :)

**Comment by MatCauthon** [comment]
Hi,

I meet the same problem and I try pip3 install layer as my environment is python 3.5.2 with tensorflow 1.0.
However, the problem can not be fixed. Any ideas?

Thanks,
Mat

**Comment by ackd06** [comment]
What happen with this error?i install layer and no error but i cant import layer with python


ubuntu@ubuntu-z:~$ pip install layer 
Requirement already satisfied: layer in ./anaconda2/lib/python2.7/site-packages
Requirement already satisfied: tensorflow in ./anaconda2/lib/python2.7/site-packages (from layer)
Requirement already satisfied: numpy>=1.11.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow->layer)
Requirement already satisfied: mock>=2.0.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow->layer)
Requirement already satisfied: six>=1.10.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow->layer)
Requirement already satisfied: wheel in ./anaconda2/lib/python2.7/site-packages (from tensorflow->layer)
Requirement already satisfied: protobuf>=3.1.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow->layer)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow->layer)
Requirement already satisfied: pbr>=0.11 in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow->layer)
Requirement already satisfied: setuptools in ./anaconda2/lib/python2.7/site-packages (from protobuf>=3.1.0->tensorflow->layer)
Requirement already satisfied: packaging>=16.8 in ./anaconda2/lib/python2.7/site-packages (from setuptools->protobuf>=3.1.0->tensorflow->layer)
Requirement already satisfied: appdirs>=1.4.0 in ./anaconda2/lib/python2.7/site-packages (from setuptools->protobuf>=3.1.0->tensorflow->layer)
Requirement already satisfied: pyparsing in ./anaconda2/lib/python2.7/site-packages (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorflow->layer)




ubuntu@ubuntu-z:~$ python
Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import layer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named layer

**Comment by saurabhvyas** [comment]
I can confirm its still a problem , I am using tf 1.0

**Comment by MatCauthon** [comment]
go to layer 's directory and you can see that there is nothing for python to import ( no .py or something like that)
I thought something was missing and we had no way to solve it.

**Comment by saurabhvyas** [comment]
So basically what are you suggesting ?

**Comment by pannous** [comment]
problem confirmed.
In the meantime do git *recursive* :

`git clone --recursive https://github.com/pannous/tensorflow-speech-recognition`

then you should see:

```
tensorflow-speech-recognition/layer$ ls
baselines.py  Clockwork_RNN.py  __init__.py  net.py  old  README.md  setup.py  tensorboard_util.py
```

**Comment by pannous** [comment]
`pip install --upgrade layer`  should now work

**Comment by hudsantos** [comment]
In my case git clone --recursive didn't do it's job. layed and tensorpeers directories remains empty and I do not know why... So I had to:
`cd tensorflow-speech-recognition`
`git clone https://github.com/pannous/layer.git`
`git clone https://github.com/pannous/tensorpeers.git`
And now I see modules there... nice! Thankyou.

**Comment by Hitesh95** [comment]
what steps are to be followed after training a set, someone please explain me

**Comment by MuruganR96** [comment]
I'm also same confusion. someone explain how to execute ?
