### ISSUE TITLE
ImportError: No module named core_rnn

### ISSUE THREAD

**Issue by liewsanmin** [pannous/tensorflow-speech-recognition#36]
Hi,

I'm trying to run `./number_classifier_tflearn.py` and the following error occurs:
`hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Traceback (most recent call last):
  File "./number_classifier_tflearn.py", line 3, in <module>
    import tflearn
  File "/usr/local/lib/python2.7/site-packages/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization
  File "/usr/local/lib/python2.7/site-packages/tflearn/layers/__init__.py", line 10, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "/usr/local/lib/python2.7/site-packages/tflearn/layers/recurrent.py", line 8, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, \
ImportError: No module named core_rnn`

Any suggestions?

OS : OSX Yosemit on Unix

**Comment by spirovykt** [comment]
You will should delete current Tensorflow version and install again. On Ubuntu it looks like:
$sudo pip uninstall tensorflow
$sudo pip install tensorflow
Pip is Python module for easy install other modules (libraries)

Maybe the following helps you in other case:
-Change interpreter of current Project (either to 3.5 or 2.7)
