### ISSUE TITLE
data is unavailable

### ISSUE THREAD

**Issue by david3012** [pannous/tensorflow-speech-recognition#58]
http://pannous.net/files/spoken_numbers_pcm.tar

Downloading from http://pannous.net/files/spoken_numbers_spectros_64x64.tar to d                                                                                                                ata/spoken_numbers_spectros_64x64.tar
Traceback (most recent call last):
  File "./speaker_classifier_tflearn.py", line 19, in <module>
    speakers = data.get_speakers()
  File "/data/home/ddonaldson/tensorflow-speech-recognition-master/speech_data.p                                                                                                                y", line 157, in get_speakers
    maybe_download(Source.DIGIT_SPECTROS)
  File "/data/home/ddonaldson/tensorflow-speech-recognition-master/speech_data.p                                                                                                                y", line 138, in maybe_download
    filepath, _ = urllib.request.urlretrieve(url_filename, filepath,progresshook                                                                                                                )
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out

it looks like the data is not available for download,
where can I get the data?

**Comment by InSightSuen** [comment]
same problem

**Comment by deepclearning** [comment]
same problem

**Comment by 4emkay** [comment]
You can download the data from here.
http://pannous.net/files/

**Comment by arnabsinha99** [comment]
> 
> 
> You can download the data from here.
> http://pannous.net/files/
> 
> In the above link you will get the all data with audio files.

This link is not working.

**Comment by JohnoverBoard** [comment]
Yes @arnabsinha99 looks like it isn't open to public anymore
