### ISSUE TITLE
Issue ./spoken_numbers_pcm.tar : This does not look like a tar archive 

### ISSUE THREAD

**Issue by khushbu9402** [pannous/tensorflow-speech-recognition#70]
Looking for data ./spoken_numbers_spectros_64x64.tar in data/
Downloading from http://pannous.net/files/./spoken_numbers_spectros_64x64.tar to data/spoken_numbers_spectros_64x64.tar
166.2% 8192 / 4930
Successfully downloaded ./spoken_numbers_spectros_64x64.tar 4930 bytes.
Extracting data/spoken_numbers_spectros_64x64.tar to data/
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Data ready!
Looking for data ./spoken_numbers_pcm.tar in data/

Downloading from http://pannous.net/files/./spoken_numbers_pcm.tar to data/spoken_numbers_pcm.tar
166.2% 8192 / 4930
Successfully downloaded ./spoken_numbers_pcm.tar 4930 bytes.
Extracting data/spoken_numbers_pcm.tar to data/
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Data ready!
Traceback (most recent call last):
  File "./speaker_classifier_tflearn.py", line 19, in <module>
    speakers = data.get_speakers()
  File "/home/vp/tensorflow-speech-recognition/speech_data.py", line 168, in get_speakers
    files = os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: 'data/spoken_numbers_pcm/'

**Comment by khushbu9402** [comment]
When I am running ./speaker_classifier_tflearn.py ,I  get the above error. Could anyone please assist me with this?Thanks.

**Comment by jgabrielgv** [comment]
Same for me

**Comment by JohnoverBoard** [comment]
I am unable to even access pannous.net/files at this point

**Comment by zernonia** [comment]
It seems like the website (pannous.net) is no longer have the those data stored.
